### ISSUE TITLE
Please update the text for Notify the editors of a mistake:

### ISSUE THREAD

**Issue by davidamichelson** [srophe/syriac-corpus-app#23]
@jedwardwalters 

Notify the editors of a mistake:

Using the following form, please inform us which page URI the mistake is on, where on the page the mistake occurs, the content of the correction, and a citation for the correct information (except in the case of obvious corrections, such as misspelled words). Please also include your email address, so that we can follow up with you regarding anything which is unclear. We will publish your name, but not your contact information as the author of the correction.
Add data to an existing entry

The Syriac Gazetteer is an ever expanding resource created by and for users. The editors actively welcome additions to the gazetteer. If there is information which you would like to add to an existing place entry in The Syriac Gazetteer, please use the link below to inform us about the information, your (primary or scholarly) source(s) for the information, and your contact information so that we can credit you for the modification. For categories of information which The Syriac Gazetteer structure can support, please see the section headings on the entry for Edessa and specify in your submission which category or categories this new information falls into. At present this information should be entered into the email form here, although there is an additional delay in this process as the data needs to be encoded in the appropriate structured data format and assigned a URI. A structured form for submitting new entries is under development.

**Comment by jedwardwalters** [comment]
@davidamichelson Here is the revised text. How does it look to you?
@wsalesky If Dave approves, this text can be used for the "Corrections/Additions" button on Syriac Corpus.

Notify the editors of a mistake:
Using the following form, please inform us which page URI the mistake is on, where on the page the mistake occurs, the content of the correction, and a citation for the correct information (except in the case of obvious corrections, such as misspelled words). Please also include your email address, so that we can follow up with you regarding anything which is unclear. We will publish your name, but not your contact information as the author of the correction.

Add data to an existing entry
The Syriac Corpus is an ever expanding resource created by and for users. The editors actively welcome additions and/or corrections to the texts or the data that accompany them. If there is information which you would like to add to an existing text entry in The Syriac Corpus, please use the link below to provide us with the information, your (primary or scholarly) source(s) for the information, and your contact information so that we can credit you for the modification. At present this information should be entered into the email form here, although there is an additional delay in this process as the data needs to be encoded in the appropriate structured data format and assigned a URI. A structured form for submitting new entries is under development.

**Comment by wsalesky** [comment]
I used this text. We can change it at any time.
