### ISSUE TITLE
Structure test

### ISSUE THREAD

**Issue by jedwardwalters** [srophe/syriac-corpus-app#45]
@dlschwartz Here's my second attempt at the Chronicle of Edessa. What do you think about this structure? Specifically about using the tei:ab within the tei:div as a way to distinguish between the two ways of viewing the text?
https://github.com/srophe/syriac-corpus/blob/master/data/tei/57.xml

**Comment by dlschwartz** [comment]
@jedwardwalters I'm debating on this still. The problem is that both the mss order and the chronological order ultimately refer to the same text structure. They are just two different ways of organizing those pieces of the text. Ideally we would apply two different numbering systems to that text structure. TEI doesn't naturally go for that though. 

I just asked a colleague and she suggested `<div2 type="section" xml:lang="syr" n="m1c8">`. Winona could then sort by the m for ms and the c for chronological.

We should talk about these options tomorrow in our meeting. will you be able to join us?

**Comment by jedwardwalters** [comment]
Okay. Yes, I’m planning to join the meeting tomorrow.

**Comment by jedwardwalters** [comment]
Closing this because I think we resolved it.
